### ISSUE TITLE
Quilt crash

### ISSUE THREAD

**Issue by lostopkk** [hibiii/Scooters#8]
https://mclo.gs/lKl5GQi

**Comment by Toon2400** [comment]
I would imagine this issue is more caused by `CameraOverhaul-1.3.1-fabric-universal` than the scooters mod, client side mods shouldn't be installed on servers

**Comment by lostopkk** [comment]
thanks

**Comment by lostopkk** [comment]
> I would imagine this issue is more caused by `CameraOverhaul-1.3.1-fabric-universal` than the scooters mod, client side mods shouldn't be installed on servers

https://mclo.gs/q8Yq88j
renders the model, but when it will use crash in the same way
